;zend_extension=xdebug.so
xdebug.start_with_request=yes
xdebug.mode=debug
;;; if you are on macOS, use host.docker.internal to identify the host machine, due to a network limitation on mac (https://docs.docker.com/docker-for-mac/networking/#port-mapping)
;;; otherwise find host ip
xdebug.client_host=host.docker.internal
;;; avoid standard port (9000) conflicts using 9005 port
xdebug.client_port=9005
xdebug.idekey=PHPStorm
